server:
  port: 8080
  servlet:
    session:
      timeout: 60m
      cookie:
        same-site: none
        secure: true

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/wherego
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: file:./uploads/,classpath:/static/

logging:
  level:
    org.springdoc: DEBUG

file:
  upload-dir: uploads

exchangerate:
  api:
    key: fe5728fe704e29678aca0e0941849c04

google:
  map:
    api_key: AIzaSyB63gpLTMYZ1RuMjpUq7S5AgnTL_B-DEXs